---
apiVersion: v1
kind: Service
metadata:
  name: fastapp
  labels:
    app: fastapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: fastapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapp
  labels:
    app: fastapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapp
  template:
    metadata:
      labels:
        app: fastapp
    spec:
      containers:
      - name: fastapp
        image: jesusaur/learn-k8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 600m
        livenessProbe:
          exec:
            command:
              - curl
              - http://localhost/ok
          initialDelaySeconds: 15
          periodSeconds: 30

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapp
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
